# Generated by Django 3.0.4 on 2020-03-31 07:35

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('grad', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('students_number', models.IntegerField()),
                ('acceptance_criteria', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EstablishmentStaff',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(max_length=150, verbose_name='Role')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.IntegerField()),
                ('feedback', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('department_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.Department')),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.Comment')),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Forum')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=250)),
                ('about', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('establishment_type', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public'), ('Semi', 'Semi')], default='Public', max_length=10, verbose_name='Private or Public')),
                ('fees', models.IntegerField(default=0, verbose_name='Fees')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('adress', models.CharField(max_length=250)),
                ('phone', models.IntegerField()),
                ('website', models.CharField(max_length=250, verbose_name='Website')),
                ('city_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.City', verbose_name='City')),
                ('director_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.EstablishmentStaff', verbose_name='Director')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='establishment_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.Establishment', verbose_name='establishment'),
        ),
        migrations.AddField(
            model_name='department',
            name='responsible_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.EstablishmentStaff', verbose_name='Responsible'),
        ),
        migrations.AddField(
            model_name='comment',
            name='department_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.Department'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='region_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.Region', verbose_name='Region'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=250)),
                ('about', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.Comment')),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
