# Generated by Django 3.0.4 on 2020-04-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='bac_plus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='discipline',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
