# Generated by Django 3.0.4 on 2020-04-14 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200407_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='establishment',
            name='abreviated_name',
            field=models.CharField(default=0, max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='establishment_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.Establishment', verbose_name='Establishment'),
        ),
        migrations.AlterField(
            model_name='department',
            name='discipline',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.Discipline', verbose_name='Discipline'),
        ),
    ]
