# Generated by Django 3.0.4 on 2020-04-14 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200414_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='region_id',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='establishment_id',
            new_name='establishment',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='responsible_id',
            new_name='responsible',
        ),
        migrations.RenameField(
            model_name='establishment',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='establishment',
            old_name='director_id',
            new_name='director',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
    ]
