# Generated by Django 3.0.4 on 2020-04-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200414_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='grad',
            field=models.CharField(choices=[('DUT', 'DUT'), ('Licence', 'Licence'), ('Master', 'Master'), ('Ingineering', 'Ingineering')], max_length=100),
        ),
    ]
